- hosts: webrecorder
  user: zoadmin
  vars:
    wr_repo: 'https://github.com/zo-edv/webrecorder'
    wr_dir: /opt/webrecorder

    wr_ldap_domain: 'ad.uni-heidelberg.de'
    wr_ldap_uri: 'ldap://{{ wr_ldap_domain }}'
    wr_ldap_base: 'DC=ad,DC=uni-heidelberg,DC=de'
    wr_ldap_admin_group: 'CN=CATS_Users_IT-WebrecorderAdmins,OU=IT-Groups,OU=Groups,OU=cats,OU=Institute,DC=ad,DC=uni-heidelberg,DC=de'
    wr_ldap_login_group: 'CN=CATS_Users_IT-WebrecorderUsers,OU=IT-Groups,OU=Groups,OU=cats,OU=Institute,DC=ad,DC=uni-heidelberg,DC=de'
    wr_review_mail: 'benedikt.koblenz@zo.uni-heidelberg.de'
    wr_smtp_url: 'starttls://anonymous@mail.urz.uni-heidelberg.de:587'
    wr_mail_sender: 'webrecorder@zo.uni-heidelberg.de'

    wr_remote_browsers:
      - 'chrome:53'
      - 'firefox:49'

    cert_key_name: '{{ wr_app_host }}'

    nginx_conf_template: "{{ playbook_dir }}/templates/nginx.conf"
    nginx_vhost_template: "{{ playbook_dir }}/templates/wrhost.conf"
    nginx_remove_default_vhost: true

    nginx_vhosts:
      - server_name: "{{ wr_content_host }}"
        filename: "{{ wr_content_host }}"
        include_ws: false

      - server_name: "{{ wr_app_host }}"
        filename: "{{ wr_app_host }}"
        include_ws: true
    pip_package: python3-pip
    pip_install_packages:
      - name: docker-compose
      - name: docker

  roles:
    - { role: geerlingguy.pip, become: true, become_user: root }
    - { role: nginx, become: true, become_user: root, when: "wr_app_host != ''" }
   # - { role: dehydrated, become: true, become_user: root, when: "wr_app_host != ''" }
    - { role: geerlingguy.docker, become: true, become_user: root }
    - { role: webrecorder_init }
